import enUS from 'ant-design-vue/es/locale/en_US';
import zhCN from 'ant-design-vue/es/locale/zh_CN';

export const LANGUAGE_LIST = {
  "zh-CN": zhCN,
  "en-US": enUS,
}

// export const LOCALE_LIST = {
//   Arabic:	'ar_EG',
//   Azerbaijani: 'az_AZ',
//   Bulgarian:	'bg_BG',
//   'Bangla (Bangladesh)':	'bn_BD',
//   Belarusian:	'by_BY',
//   Catalan: 'ca_ES',
//   Czech: 'cs_CZ',
//   Danish:	'da_DK',
//   German:	'de_DE',
//   Greek: 'el_GR',
//   'English (United Kingdom)':	'en_GB',
//   English:	'en_US',
//   Spanish:	'es_ES',
//   Estonian:	'et_EE',
//   Persian:	'fa_IR',
//   Finnish:	'fi_FI',
//   'French (Belgium)':	'fr_BE',
//   'French (Canada)':	'fr_CA',
//   'French (France)':	'fr_FR',
//   'Irish (Ireland)':	'ga_IE',
//   'Galician (Spain)':	'gl_ES',
//   Hebrew:	'he_IL',
//   Hindi:	'hi_IN',
//   Croatian:	'hr_HR',
//   Hungarian:	'hu_HU',
//   Armenian:	'hy_AM',
//   Indonesian:	'id_ID',
//   Italian:	'it_IT',
//   Icelandic:	'is_IS',
//   Japanese:	'ja_JP',
//   Georgian:	'ka_GE',
//   'Kurdish (Kurmanji)':	'kmr_IQ',
//   Kannada:	'kn_IN',
//   Kazakh:	'kk_KZ',
//   Khmer:	'km_KH',
//   Korean:	'ko_KR',
//   Lithuanian:	'lt_LT',
//   Latvian:	'lv_LV',
//   Macedonian:	'mk_MK',
//   'Malayalam (India)':	'ml_IN',
//   Mongolian:	'mn_MN',
//   'Malay (Malaysia)':	'ms_MY',
//   Norwegian:	'nb_NO',
//   Nepal:	'ne_NP',
//   'Dutch (Belgium)':	'nl_BE',
//   Dutch:	'nl_NL',
//   Polish:	'pl_PL',
//   'Portuguese (Brazil)':	'pt_BR',
//   Portuguese:	'pt_PT',
//   Romanian:	'ro_RO',
//   Russian:	'ru_RU',
//   Slovak:	'sk_SK',
//   Serbian:	'sr_RS',
//   Slovenian:	'sl_SI',
//   Swedish:	'sv_SE',
//   Tamil:	'ta_IN',
//   Thai:	'th_TH',
//   Turkish:	'tr_TR',
//   'Urdu (Pakistan)':	'ur_PK',
//   Ukrainian:	'uk_UA',
//   Vietnamese:	'vi_VN',
//   'Chinese (Simplified)': 'zh_CN',
//   'Chinese (Traditional)':'zh_HK',
//   'Chinese (Traditional) ': 'zh_TW',
// }