// import { resOrders, resPendingOrders, resHistoryOrders } from "api/order/index";

export const tableColumns: any = {
  marketOrder: [
    { title: "订单ID", dataKey: "id", key: "id", width: 100, align: "left" },
    {
      title: "交易品种",
      dataKey: "symbol",
      key: "symbol",
      width: 120,
      align: "right",
    },
    {
      title: "方向",
      dataKey: "type",
      key: "type",
      width: 100,
      align: "right",
    },
    {
      title: "建仓时间 (UTC+8)",
      dataKey: "time_setup",
      key: "time_setup",
      width: 200,
      align: "right",
    },
    {
      title: "手数",
      dataKey: "volume",
      key: "volume",
      width: 100,
      align: "right",
    },
    // {
    //   title: "合约数量",
    //   dataKey: "contract_size",
    //   key: "contract_size",
    //   width: 100,
    // ,align: 'right'},
    {
      title: "止盈",
      dataKey: "tp_price",
      key: "tp_price",
      width: 110,
      align: "right",
    },
    {
      title: "止损",
      dataKey: "sl_price",
      key: "sl_price",
      width: 110,
      align: "right",
    },
    {
      title: "入场价",
      dataKey: "open_price",
      key: "open_price",
      width: 110,
      align: "right",
    },
    {
      title: "当前价",
      dataKey: "now_price",
      key: "now_price",
      width: 110,
      align: "right",
    },
    {
      title: "过夜费",
      dataKey: "storage",
      key: "storage",
      width: 110,
      align: "right",
    },
    { title: "手续费", dataKey: "fee", key: "fee", width: 110, align: "right" },
    {
      title: "持仓天数",
      dataKey: "days",
      key: "days",
      width: 110,
      align: "right",
    },
    {
      title: "备注",
      dataKey: "comment",
      key: "comment",
      width: 110,
      align: "right",
    },
    {
      title: "盈亏",
      dataKey: "profit",
      key: "profit",
      width: 110,
      align: "right",
    },
    {
      dataKey: "positionAction",
      key: "action",
      width: 40,
      align: "center",
      minWidth: 40,
    },
  ],
  pendingOrder: [
    { title: "订单ID", dataKey: "id", key: "id", width: 100, align: "left" },
    {
      title: "交易品种",
      dataKey: "symbol",
      key: "symbol",
      width: 120,
      align: "right",
    },
    {
      title: "订单类型",
      dataKey: "orderType",
      key: "orderType",
      width: 110,
      align: "right",
    },
    {
      title: "建仓时间（UTC+8）",
      dataKey: "time_setup",
      key: "time_setup",
      width: 200,
      align: "right",
    },
    // {
    //   title: "方向",
    //   dataKey: "type",
    //   key: "type",
    //   width: 100,
    //   sorter: (a: resPendingOrders, b: resPendingOrders) => a.type - b.type,
    // ,align: 'right'},
    {
      title: "手数",
      dataKey: "volume",
      key: "volume",
      width: 110,
      align: "right",
    },
    {
      title: "挂单价格",
      dataKey: "order_price",
      key: "order_price",
      width: 110,
      align: "right",
    },
    // {
    //   title: "限制价位",
    //   dataKey: "trigger_price",
    //   key: "trigger_price",
    //   width: 110,
    // ,align: 'right'},
    {
      title: "当前价格",
      dataKey: "now_price",
      key: "now_price",
      width: 100,
      align: "right",
    },
    {
      title: "止盈",
      dataKey: "tp_price",
      key: "tp_price",
      width: 100,
      align: "right",
    },
    {
      title: "止损",
      dataKey: "sl_price",
      key: "sl_price",
      width: 100,
      align: "right",
    },
    {
      title: "到期时间",
      dataKey: "time_expiration",
      key: "time_expiration",
      width: 200,
      align: "right",
    },
    {
      dataKey: "orderAction",
      key: "action",
      width: 40,
      align: "center",
      minWidth: 40,
    },
  ],
  // 挂单历史
  pendingOrderHistory: [
    { title: "订单ID", dataKey: "id", key: "id", width: 100, align: "left" },
    {
      title: "交易品种",
      dataKey: "symbol",
      key: "symbol",
      width: 120,
      align: "right",
    },
    {
      title: "订单类型",
      dataKey: "orderType",
      key: "orderType",
      width: 110,
      align: "right",
    },
    {
      title: "挂单时间（UTC+8）",
      dataKey: "time_setup",
      key: "time_setup",
      width: 200,
      align: "right",
    },
    {
      title: "手数",
      dataKey: "volume",
      key: "volume",
      width: 100,
      align: "right",
    },
    {
      title: "挂单价格",
      dataKey: "order_price",
      key: "order_price",
      width: 110,
      align: "right",
    },
    // {
    //   title: "方向",
    //   dataKey: "type",
    //   key: "type",
    //   width: 100,
    //   sorter: (a: resPendingOrders, b: resPendingOrders) => a.type - b.type,
    // ,align: 'right'},
    // {
    //   title: "限制价位",
    //   dataKey: "trigger_price",
    //   key: "trigger_price",
    //   width: 110,
    // ,align: 'right'},
    {
      title: "止盈",
      dataKey: "tp_price",
      key: "tp_price",
      width: 100,
      align: "right",
    },
    {
      title: "止损",
      dataKey: "sl_price",
      key: "sl_price",
      width: 100,
      align: "right",
    },
    {
      title: "到期时间",
      dataKey: "time_expiration",
      key: "time_expiration",
      width: 200,
      align: "right",
    },
    {
      title: "关闭时间",
      dataKey: "time_done",
      key: "time_done",
      width: 200,
      align: "right",
    },
  ],
  // 持仓历史
  marketOrderHistory: [
    { title: "订单ID", dataKey: "id", key: "id", width: 100, align: "left" },
    {
      title: "交易品种",
      dataKey: "symbol",
      key: "symbol",
      width: 120,
      align: "right",
    },
    {
      title: "方向",
      dataKey: "type",
      key: "type",
      width: 80,
      align: "right",
    },
    {
      title: "建仓时间（UTC+8）",
      dataKey: "time_setup",
      key: "open_time",
      width: 200,
      align: "right",
    },
    {
      title: "入场价",
      dataKey: "open_price",
      key: "open_price",
      width: 110,
      align: "right",
    },
    {
      title: "手数",
      dataKey: "volume",
      key: "volume",
      width: 80,
      align: "right",
    },
    {
      title: "止盈",
      dataKey: "tp_price",
      key: "tp_price",
      width: 100,
      align: "right",
    },
    {
      title: "止损",
      dataKey: "sl_price",
      key: "sl_price",
      width: 100,
      align: "right",
    },
    {
      title: "平仓ID",
      dataKey: "from_id",
      key: "from_id",
      width: 130,
      align: "right",
    },
    {
      title: "平仓价",
      dataKey: "close_price",
      key: "close_price",
      width: 110,
      align: "right",
    },
    {
      title: "平仓类型",
      dataKey: "close_type",
      key: "close_type",
      width: 100,
      align: "right",
    },
    {
      title: "盈亏",
      dataKey: "profit",
      key: "profit",
      width: 110,
      align: "right",
    },
    // {
    //   title: "最初的建仓订单",
    //   dataKey: "position_id",
    //   key: "position_id",
    //   width: 130,
    // ,align: 'right'},
    // {
    //   title: "结束时间（UTC+8）",
    //   dataKey: "time_done",
    //   key: "time_done",
    //   width: 200,
    // ,align: 'right'},
    {
      title: "过夜费",
      dataKey: "storage",
      key: "storage",
      width: 100,
      align: "right",
    },
    { title: "手续费", dataKey: "fee", key: "fee", width: 100, align: "right" },
    {
      title: "持仓天数",
      dataKey: "days",
      key: "days",
      width: 100,
      align: "right",
    },
    // { title: "备注", dataKey: "comment", key: "comment", width: 100 ,align: 'right'},
  ],
  blanceRecord: [
    { title: "订单ID", dataKey: "id", key: "id", width: 100, align: "left" },
    {
      title: "时间（UTC+8）",
      dataKey: "time_setup",
      key: "open_time",
      width: 200,
      align: "right",
    },
    {
      title: "金额",
      dataKey: "profit",
      key: "blance",
      width: 110,
      align: "right",
    },
    {
      title: "交易类型",
      dataKey: "blanceType",
      key: "blanceType",
      width: 110,
      align: "right",
    },
    {
      title: "备注",
      dataKey: "comment",
      key: "comment",
      width: 200,
      align: "right",
    },
  ],
};
