// import { resOrders, resPendingOrders, resHistoryOrders } from "api/order/index";

export const tableColumns: any = {
  marketOrder: [
    {
      title: "交易品种",
      dataKey: "symbol",
      key: "symbol",
      width: 120,
    },
    { title: "订单ID", dataKey: "id", key: "id", width: 100 },
    {
      title: "方向",
      dataKey: "type",
      key: "type",
      width: 100,
    },
    {
      title: "建仓时间 (UTC+8)",
      dataKey: "time_setup",
      key: "time_setup",
      width: 200,
    },
    { title: "手数", dataKey: "volume", key: "volume", width: 100 },
    // {
    //   title: "合约数量",
    //   dataKey: "contract_size",
    //   key: "contract_size",
    //   width: 100,
    // },
    { title: "止盈", dataKey: "tp_price", key: "tp_price", width: 110 },
    { title: "止损", dataKey: "sl_price", key: "sl_price", width: 110 },
    { title: "入场价", dataKey: "open_price", key: "open_price", width: 110 },
    { title: "当前价", dataKey: "now_price", key: "now_price", width: 110 },
    {
      title: "盈亏",
      dataKey: "profit",
      key: "profit",
      width: 110,
    },
    { title: "过夜费", dataKey: "storage", key: "storage", width: 110 },
    { title: "手续费", dataKey: "fee", key: "fee", width: 110 },
    { title: "持仓天数", dataKey: "days", key: "days", width: 110 },
    {
      dataKey: "positionAction",
      key: "positionAction",
      width: 30,
      align: "center",
    },
  ],
  pendingOrder: [
    {
      title: "交易品种",
      dataKey: "symbol",
      key: "symbol",
      width: 120,
    },
    { title: "订单ID", dataKey: "id", key: "id", width: 100 },
    { title: "订单类型", dataKey: "orderType", key: "orderType", width: 110 },
    {
      title: "建仓时间（UTC+8）",
      dataKey: "time_setup",
      key: "time_setup",
      width: 200,
    },
    // {
    //   title: "方向",
    //   dataKey: "type",
    //   key: "type",
    //   width: 100,
    //   sorter: (a: resPendingOrders, b: resPendingOrders) => a.type - b.type,
    // },
    { title: "手数", dataKey: "volume", key: "volume", width: 110 },
    {
      title: "挂单价格",
      dataKey: "order_price",
      key: "order_price",
      width: 110,
    },
    // {
    //   title: "限制价位",
    //   dataKey: "trigger_price",
    //   key: "trigger_price",
    //   width: 110,
    // },
    { title: "当前价格", dataKey: "now_price", key: "now_price", width: 100 },
    { title: "止盈", dataKey: "tp_price", key: "tp_price", width: 100 },
    { title: "止损", dataKey: "sl_price", key: "sl_price", width: 100 },
    {
      title: "到期时间",
      dataKey: "time_expiration",
      key: "time_expiration",
      width: 200,
    },
    {
      dataKey: "orderAction",
      key: "orderAction",
      width: 30,
      align: "center",
    },
  ],
  // 挂单历史
  pendingOrderHistory: [
    { title: "订单ID", dataKey: "id", key: "id", width: 100 },
    {
      title: "交易品种",
      dataKey: "symbol",
      key: "symbol",
      width: 120,
    },
    { title: "订单类型", dataKey: "orderType", key: "orderType", width: 110 },
    {
      title: "挂单时间（UTC+8）",
      dataKey: "time_setup",
      key: "time_setup",
      width: 200,
    },
    { title: "手数", dataKey: "volume", key: "volume", width: 100 },
    {
      title: "挂单价格",
      dataKey: "order_price",
      key: "order_price",
      width: 110,
    },
    // {
    //   title: "方向",
    //   dataKey: "type",
    //   key: "type",
    //   width: 100,
    //   sorter: (a: resPendingOrders, b: resPendingOrders) => a.type - b.type,
    // },
    // {
    //   title: "限制价位",
    //   dataKey: "trigger_price",
    //   key: "trigger_price",
    //   width: 110,
    // },
    { title: "止盈", dataKey: "tp_price", key: "tp_price", width: 100 },
    { title: "止损", dataKey: "sl_price", key: "sl_price", width: 100 },
    {
      title: "到期时间",
      dataKey: "time_expiration",
      key: "time_expiration",
      width: 200,
    },
    {
      title: "关闭时间",
      dataKey: "time_done",
      key: "time_done",
      width: 200,
    },
  ],
  // 持仓历史
  marketOrderHistory: [
    { title: "订单ID", dataKey: "id", key: "id", width: 100 },
    {
      title: "交易品种",
      dataKey: "symbol",
      key: "symbol",
      width: 120,
    },
    {
      title: "方向",
      dataKey: "type",
      key: "type",
      width: 80,
    },
    {
      title: "建仓时间（UTC+8）",
      dataKey: "time_setup",
      key: "open_time",
      width: 200,
    },
    {
      title: "入场价",
      dataKey: "open_price",
      key: "open_price",
      width: 110,
    },
    { title: "手数", dataKey: "volume", key: "volume", width: 80 },
    { title: "止盈", dataKey: "tp_price", key: "tp_price", width: 100 },
    { title: "止损", dataKey: "sl_price", key: "sl_price", width: 100 },
    { title: "平仓ID", dataKey: "from_id", key: "from_id", width: 130 },
    {
      title: "平仓价",
      dataKey: "close_price",
      key: "close_price",
      width: 110,
    },
    {
      title: "平仓类型",
      dataKey: "close_type",
      key: "close_type",
      width: 100,
    },
    {
      title: "盈亏",
      dataKey: "profit",
      key: "profit",
      width: 110,
    },
    // {
    //   title: "最初的建仓订单",
    //   dataKey: "position_id",
    //   key: "position_id",
    //   width: 130,
    // },
    // {
    //   title: "结束时间（UTC+8）",
    //   dataKey: "time_done",
    //   key: "time_done",
    //   width: 200,
    // },
    { title: "过夜费", dataKey: "storage", key: "storage", width: 100 },
    { title: "手续费", dataKey: "fee", key: "fee", width: 100 },
    { title: "持仓天数", dataKey: "days", key: "days", width: 100 },
    // { title: "备注", dataKey: "comment", key: "comment", width: 100 },
  ],
  blanceRecord: [
    { title: "订单ID", dataKey: "id", key: "id", width: 100 },
    {
      title: "时间（UTC+8）",
      dataKey: "time_setup",
      key: "open_time",
      width: 200,
    },
    {
      title: "金额",
      dataKey: "profit",
      key: "blance",
      width: 110,
    },
    {
      title: "交易类型",
      dataKey: "blanceType",
      key: "blanceType",
      width: 110,
    },
    { title: "备注", dataKey: "comment", key: "comment", width: 200 },
  ],
};
